# Generated by Django 4.0.5 on 2022-06-08 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_child'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'Child', 'verbose_name_plural': 'MY CHILD'},
        ),
    ]
