# Generated by Django 4.0.5 on 2022-06-08 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_child_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='child',
            table='new',
        ),
    ]
