# Generated by Django 4.0.5 on 2022-06-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_child_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='weight',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
