# Generated by Django 4.0.5 on 2022-06-08 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_child_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={},
        ),
    ]
