# Generated by Django 4.0.5 on 2022-06-08 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_child_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'boy', 'verbose_name_plural': 'MY CHILD'},
        ),
    ]
